# Generated by Django 3.0.3 on 2020-09-13 09:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_job_data_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='progress',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
