# Generated by Django 3.0.3 on 2020-12-17 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_job_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='evaluation',
        ),
        migrations.RemoveField(
            model_name='job',
            name='evaluation_params',
        ),
    ]
