# Generated by Django 3.0.2 on 2020-01-18 13:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=50)),
                ('algorithm_name', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('queued', 'In Queue'), ('in_progress', 'In Progress'), ('finished', 'Finished'), ('failed', 'Failed')], default='queued', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('started_at', models.DateTimeField(null=True, verbose_name='date started')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last update date')),
                ('finished_at', models.DateTimeField(null=True, verbose_name='date finished')),
                ('dataset_params', django.contrib.postgres.fields.jsonb.JSONField()),
                ('algorithm_params', django.contrib.postgres.fields.jsonb.JSONField()),
                ('results', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
