# Generated by Django 3.0.3 on 2020-05-27 13:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_job_evaluation_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='data_summary',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
